### ISSUE TITLE
Seem it working incorrect with custom field in Settings

### ISSUE THREAD

**Issue by kidesigner** [alleyinteractive/options-importer#6]
I add Icon for Category, use custom field options, when i use this plugin seem it working incorrect.

**Comment by mboynes** [comment]
Hi @kidesigner, I would need more information to advise you on what the issue is.

Most likely, if you added an icon, what's stored in the options table is an attachment ID. The option importer will move that attachment ID over, but it has no understanding that that's a reference to an image (it just sees an integer), and therefore it doesn't download the attachment. Therefore, the attachment would need to be moved over separately. _However_, the attachment moved over would need to have an identical ID as the old one. This is possible if you've moved the site content via export/import, but highly unlikely otherwise.

All this to say, for that one specific option, you'll probably have to set it manually unless you were also migrating content (and in some cases, even if you did).
